[2023-09-10T11:04:47.325+0000] {processor.py:157} INFO - Started process (PID=441) to work on /opt/airflow/dags/new_file_sensor.py
[2023-09-10T11:04:47.326+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/new_file_sensor.py for tasks to queue
[2023-09-10T11:04:47.327+0000] {logging_mixin.py:151} INFO - [2023-09-10T11:04:47.327+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/new_file_sensor.py
[2023-09-10T11:04:47.337+0000] {logging_mixin.py:151} INFO - [2023-09-10T11:04:47.336+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/new_file_sensor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/new_file_sensor.py", line 4, in <module>
    from airflow.operators.trigger_dagrun import TriggerDagRun
ImportError: cannot import name 'TriggerDagRun' from 'airflow.operators.trigger_dagrun' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py)
[2023-09-10T11:04:47.338+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/new_file_sensor.py
[2023-09-10T11:04:47.359+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/new_file_sensor.py took 0.039 seconds
[2023-09-10T11:05:17.529+0000] {processor.py:157} INFO - Started process (PID=452) to work on /opt/airflow/dags/new_file_sensor.py
[2023-09-10T11:05:17.531+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/new_file_sensor.py for tasks to queue
[2023-09-10T11:05:17.532+0000] {logging_mixin.py:151} INFO - [2023-09-10T11:05:17.532+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/new_file_sensor.py
[2023-09-10T11:05:17.541+0000] {logging_mixin.py:151} INFO - [2023-09-10T11:05:17.539+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/new_file_sensor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/new_file_sensor.py", line 4, in <module>
    from airflow.operators.trigger_dagrun import TriggerDagRun
ImportError: cannot import name 'TriggerDagRun' from 'airflow.operators.trigger_dagrun' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py)
[2023-09-10T11:05:17.542+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/new_file_sensor.py
[2023-09-10T11:05:17.564+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/new_file_sensor.py took 0.040 seconds
[2023-09-10T11:05:45.823+0000] {processor.py:157} INFO - Started process (PID=463) to work on /opt/airflow/dags/new_file_sensor.py
[2023-09-10T11:05:45.825+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/new_file_sensor.py for tasks to queue
[2023-09-10T11:05:45.826+0000] {logging_mixin.py:151} INFO - [2023-09-10T11:05:45.826+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/new_file_sensor.py
[2023-09-10T11:05:45.837+0000] {logging_mixin.py:151} INFO - [2023-09-10T11:05:45.835+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/new_file_sensor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/new_file_sensor.py", line 4, in <module>
    from airflow.operators.trigger_dagrun import TriggerDagRun
ImportError: cannot import name 'TriggerDagRun' from 'airflow.operators.trigger_dagrun' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py)
[2023-09-10T11:05:45.838+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/new_file_sensor.py
[2023-09-10T11:05:45.857+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/new_file_sensor.py took 0.038 seconds
