[2023-09-08T15:48:25.610+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:48:25.611+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:48:25.615+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:48:25.615+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:48:25.661+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:48:25.653+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:48:25.663+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:48:25.680+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.074 seconds
[2023-09-08T15:48:55.909+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:48:55.911+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:48:55.914+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:48:55.914+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:48:55.929+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:48:55.927+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:48:55.930+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:48:55.974+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.069 seconds
[2023-09-08T15:49:26.271+0000] {processor.py:157} INFO - Started process (PID=61) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:49:26.273+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:49:26.276+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:49:26.275+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:49:26.288+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:49:26.286+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:49:26.289+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:49:26.322+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.054 seconds
[2023-09-08T15:49:56.628+0000] {processor.py:157} INFO - Started process (PID=72) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:49:56.629+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:49:56.632+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:49:56.632+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:49:56.643+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:49:56.641+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:49:56.645+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:49:56.665+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.041 seconds
[2023-09-08T15:50:26.941+0000] {processor.py:157} INFO - Started process (PID=83) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:50:26.942+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:50:26.944+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:50:26.943+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:50:26.958+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:50:26.955+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:50:26.958+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:50:26.979+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.043 seconds
[2023-09-08T15:50:57.223+0000] {processor.py:157} INFO - Started process (PID=93) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:50:57.225+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:50:57.226+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:50:57.226+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:50:57.239+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:50:57.236+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:50:57.240+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:50:57.260+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.043 seconds
[2023-09-08T15:51:27.525+0000] {processor.py:157} INFO - Started process (PID=103) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:51:27.543+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:51:27.544+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:51:27.544+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:51:27.557+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:51:27.554+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:51:27.558+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:51:27.577+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.056 seconds
[2023-09-08T15:51:57.842+0000] {processor.py:157} INFO - Started process (PID=113) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:51:57.844+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:51:57.845+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:51:57.845+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:51:57.860+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:51:57.856+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:51:57.861+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:51:57.883+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.046 seconds
[2023-09-08T15:52:28.127+0000] {processor.py:157} INFO - Started process (PID=123) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:52:28.129+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:52:28.131+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:52:28.130+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:52:28.145+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:52:28.142+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:52:28.146+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:52:28.166+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.044 seconds
[2023-09-08T15:52:58.395+0000] {processor.py:157} INFO - Started process (PID=133) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:52:58.397+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:52:58.398+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:52:58.398+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:52:58.412+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:52:58.410+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:52:58.413+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:52:58.433+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.043 seconds
[2023-09-08T15:53:28.756+0000] {processor.py:157} INFO - Started process (PID=143) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:53:28.758+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:53:28.759+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:53:28.759+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:53:28.772+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:53:28.769+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:53:28.773+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:53:28.792+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.039 seconds
[2023-09-08T15:53:59.049+0000] {processor.py:157} INFO - Started process (PID=153) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:53:59.051+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:53:59.053+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:53:59.053+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:53:59.070+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:53:59.068+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:53:59.071+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:53:59.090+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.046 seconds
[2023-09-08T15:54:29.332+0000] {processor.py:157} INFO - Started process (PID=163) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:54:29.334+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:54:29.335+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:54:29.335+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:54:29.349+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:54:29.347+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:54:29.350+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:54:29.370+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.042 seconds
[2023-09-08T15:54:59.626+0000] {processor.py:157} INFO - Started process (PID=173) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:54:59.628+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:54:59.630+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:54:59.629+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:54:59.644+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:54:59.641+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:54:59.646+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:54:59.668+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.047 seconds
[2023-09-08T15:55:29.944+0000] {processor.py:157} INFO - Started process (PID=190) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:55:29.945+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:55:29.947+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:55:29.947+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:55:29.961+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:55:29.958+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:55:29.962+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:55:29.984+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.044 seconds
[2023-09-08T15:56:00.257+0000] {processor.py:157} INFO - Started process (PID=200) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:56:00.262+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:56:00.264+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:56:00.264+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:56:00.281+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:56:00.279+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:56:00.283+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:56:00.305+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.052 seconds
[2023-09-08T15:56:30.560+0000] {processor.py:157} INFO - Started process (PID=212) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:56:30.561+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:56:30.562+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:56:30.562+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:56:30.597+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:56:30.594+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:56:30.598+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:56:30.621+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.065 seconds
[2023-09-08T15:57:00.835+0000] {processor.py:157} INFO - Started process (PID=223) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:57:00.837+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:57:00.838+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:57:00.838+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:57:00.852+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:57:00.850+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:57:00.853+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:57:00.872+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.042 seconds
[2023-09-08T15:57:08.942+0000] {processor.py:157} INFO - Started process (PID=225) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:57:08.944+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T15:57:08.945+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:57:08.945+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:57:08.960+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:57:08.958+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:57:08.961+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T15:57:08.978+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.039 seconds
[2023-09-08T16:01:36.485+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:01:36.487+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T16:01:36.492+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:01:36.492+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:01:36.509+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:01:36.504+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:01:36.511+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:01:36.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.053 seconds
[2023-09-08T16:02:07.363+0000] {processor.py:157} INFO - Started process (PID=51) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:02:07.365+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T16:02:07.369+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:02:07.369+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:02:07.382+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:02:07.380+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:02:07.383+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:02:07.404+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.045 seconds
[2023-09-08T16:02:38.096+0000] {processor.py:157} INFO - Started process (PID=64) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:02:38.097+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T16:02:38.101+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:02:38.101+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:02:38.113+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:02:38.110+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:02:38.114+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:02:38.133+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.041 seconds
[2023-09-08T16:03:08.778+0000] {processor.py:157} INFO - Started process (PID=77) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:03:08.780+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T16:03:08.784+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:03:08.783+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:03:08.798+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:03:08.795+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:03:08.798+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:03:08.817+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.043 seconds
[2023-09-08T16:03:39.453+0000] {processor.py:157} INFO - Started process (PID=90) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:03:39.455+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T16:03:39.458+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:03:39.457+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:03:39.473+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:03:39.469+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:03:39.474+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:03:39.497+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.048 seconds
[2023-09-08T16:04:10.139+0000] {processor.py:157} INFO - Started process (PID=103) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:04:10.141+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T16:04:10.144+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:04:10.143+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:04:10.156+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:04:10.153+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:04:10.157+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:04:10.177+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.042 seconds
[2023-09-08T16:04:40.845+0000] {processor.py:157} INFO - Started process (PID=116) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:04:40.847+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T16:04:40.852+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:04:40.851+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:04:40.869+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:04:40.866+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:04:40.869+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:04:40.889+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.048 seconds
[2023-09-08T16:05:11.566+0000] {processor.py:157} INFO - Started process (PID=129) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:05:11.568+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T16:05:11.572+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:05:11.571+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:05:11.713+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:05:11.710+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:05:11.714+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:05:11.732+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.171 seconds
[2023-09-08T16:05:42.286+0000] {processor.py:157} INFO - Started process (PID=143) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:05:42.287+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T16:05:42.291+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:05:42.291+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:05:42.307+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:05:42.303+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:05:42.308+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:05:42.333+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.052 seconds
[2023-09-08T16:06:12.945+0000] {processor.py:157} INFO - Started process (PID=156) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:06:12.947+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T16:06:12.951+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:06:12.950+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:06:12.964+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:06:12.962+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:06:12.982+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:06:13.001+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.060 seconds
[2023-09-08T16:06:43.113+0000] {processor.py:157} INFO - Started process (PID=173) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:06:43.115+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T16:06:43.119+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:06:43.119+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:06:43.135+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:06:43.133+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:06:43.136+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:06:43.156+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.046 seconds
[2023-09-08T16:07:22.452+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:07:22.454+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T16:07:22.457+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:07:22.457+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:07:22.469+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:07:22.467+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:07:22.470+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:07:22.493+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.045 seconds
[2023-09-08T16:07:53.262+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:07:53.264+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T16:07:53.267+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:07:53.267+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:07:53.280+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:07:53.278+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:07:53.281+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:07:53.301+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.043 seconds
[2023-09-08T16:08:24.003+0000] {processor.py:157} INFO - Started process (PID=68) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:08:24.004+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T16:08:24.007+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:08:24.007+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:08:24.018+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:08:24.016+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:08:24.019+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T16:08:24.038+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.039 seconds
[2023-09-08T17:45:26.014+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:45:26.016+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:45:26.019+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:45:26.019+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:45:26.038+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:45:26.035+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:45:26.039+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:45:26.062+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.053 seconds
[2023-09-08T17:45:56.762+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:45:56.763+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:45:56.765+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:45:56.765+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:45:56.778+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:45:56.775+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:45:56.779+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:45:56.798+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.040 seconds
[2023-09-08T17:46:27.436+0000] {processor.py:157} INFO - Started process (PID=68) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:46:27.438+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:46:27.441+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:46:27.440+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:46:27.452+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:46:27.450+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:46:27.453+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:46:27.471+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.039 seconds
[2023-09-08T17:46:58.269+0000] {processor.py:157} INFO - Started process (PID=81) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:46:58.271+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:46:58.273+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:46:58.273+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:46:58.286+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:46:58.283+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:46:58.287+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:46:58.307+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.043 seconds
[2023-09-08T17:47:29.016+0000] {processor.py:157} INFO - Started process (PID=94) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:47:29.017+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:47:29.020+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:47:29.019+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:47:29.031+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:47:29.029+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:47:29.032+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:47:29.050+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.038 seconds
[2023-09-08T17:47:59.725+0000] {processor.py:157} INFO - Started process (PID=107) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:47:59.726+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:47:59.729+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:47:59.729+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:47:59.740+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:47:59.738+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:47:59.741+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:47:59.759+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.037 seconds
[2023-09-08T17:48:30.377+0000] {processor.py:157} INFO - Started process (PID=120) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:48:30.379+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:48:30.381+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:48:30.381+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:48:30.392+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:48:30.390+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:48:30.393+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:48:30.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.038 seconds
[2023-09-08T17:49:01.172+0000] {processor.py:157} INFO - Started process (PID=133) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:49:01.173+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:49:01.176+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:49:01.175+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:49:01.299+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:49:01.296+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:49:01.301+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:49:01.320+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.152 seconds
[2023-09-08T17:49:32.070+0000] {processor.py:157} INFO - Started process (PID=146) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:49:32.072+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:49:32.076+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:49:32.075+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:49:32.089+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:49:32.087+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:49:32.090+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:49:32.111+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.045 seconds
[2023-09-08T17:50:02.743+0000] {processor.py:157} INFO - Started process (PID=159) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:50:02.744+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:50:02.748+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:50:02.747+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:50:02.760+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:50:02.758+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:50:02.761+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:50:02.779+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.040 seconds
[2023-09-08T17:50:33.416+0000] {processor.py:157} INFO - Started process (PID=172) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:50:33.418+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:50:33.421+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:50:33.420+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:50:33.432+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:50:33.430+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:50:33.433+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:50:33.449+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.038 seconds
[2023-09-08T17:51:04.023+0000] {processor.py:157} INFO - Started process (PID=185) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:51:04.024+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:51:04.027+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:51:04.027+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:51:04.039+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:51:04.037+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
  File "/opt/airflow/dags/create_tables_psql.py", line 75, in <module>
    create_table_if_not_exists('country_data', COUNTRY_DATA_SCHEMA)
  File "/opt/airflow/dags/create_tables_psql.py", line 57, in create_table_if_not_exists
    conn = psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:51:04.041+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:51:04.061+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.042 seconds
[2023-09-08T17:51:34.366+0000] {processor.py:157} INFO - Started process (PID=197) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:51:34.382+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:51:34.385+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:51:34.385+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:51:34.539+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:51:34.537+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:51:34.540+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:51:34.561+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.198 seconds
[2023-09-08T17:52:22.972+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:52:22.974+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:52:22.978+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:52:22.977+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:52:23.057+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:52:23.055+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:52:23.058+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:52:23.084+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.116 seconds
[2023-09-08T17:52:53.835+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:52:53.836+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:52:53.839+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:52:53.839+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:52:53.902+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:52:53.900+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:52:53.903+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:52:53.923+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.092 seconds
[2023-09-08T17:53:24.648+0000] {processor.py:157} INFO - Started process (PID=68) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:53:24.649+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:53:24.651+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:53:24.651+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:53:24.708+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:53:24.706+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:53:24.709+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:53:24.728+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.084 seconds
[2023-09-08T17:53:55.457+0000] {processor.py:157} INFO - Started process (PID=81) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:53:55.458+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:53:55.461+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:53:55.461+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:53:55.520+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:53:55.518+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:53:55.521+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:53:55.539+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.086 seconds
[2023-09-08T17:54:26.209+0000] {processor.py:157} INFO - Started process (PID=94) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:54:26.211+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:54:26.214+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:54:26.213+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:54:26.270+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:54:26.269+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:54:26.271+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:54:26.290+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.085 seconds
[2023-09-08T17:55:43.857+0000] {processor.py:157} INFO - Started process (PID=45) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:55:43.859+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:55:43.862+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:55:43.862+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:55:43.931+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:55:43.928+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:55:43.932+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:55:43.951+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.098 seconds
[2023-09-08T17:56:14.948+0000] {processor.py:157} INFO - Started process (PID=58) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:56:14.950+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:56:14.954+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:56:14.953+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:56:15.018+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:56:15.015+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:56:15.019+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:56:15.039+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.094 seconds
[2023-09-08T17:56:46.018+0000] {processor.py:157} INFO - Started process (PID=71) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:56:46.020+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:56:46.023+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:56:46.022+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:56:46.091+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:56:46.088+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:56:46.092+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:56:46.113+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.099 seconds
[2023-09-08T17:57:17.052+0000] {processor.py:157} INFO - Started process (PID=84) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:57:17.053+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:57:17.056+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:57:17.055+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:57:17.243+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:57:17.241+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:57:17.244+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:57:17.260+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.213 seconds
[2023-09-08T17:57:48.062+0000] {processor.py:157} INFO - Started process (PID=104) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:57:48.064+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:57:48.067+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:57:48.066+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:57:48.127+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:57:48.125+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:57:48.129+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:57:48.153+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.095 seconds
[2023-09-08T17:58:18.937+0000] {processor.py:157} INFO - Started process (PID=117) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:58:18.939+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:58:18.942+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:58:18.942+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:58:19.002+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:58:18.999+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:58:19.004+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:58:19.027+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.094 seconds
[2023-09-08T17:58:49.736+0000] {processor.py:157} INFO - Started process (PID=130) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:58:49.738+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:58:49.742+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:58:49.742+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:58:49.805+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:58:49.803+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:58:49.806+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:58:49.826+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.094 seconds
[2023-09-08T17:59:20.590+0000] {processor.py:157} INFO - Started process (PID=143) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:59:20.592+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:59:20.595+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:59:20.595+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:59:20.658+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:59:20.656+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:59:20.660+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:59:20.680+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.095 seconds
[2023-09-08T17:59:51.564+0000] {processor.py:157} INFO - Started process (PID=157) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:59:51.566+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T17:59:51.571+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:59:51.570+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:59:51.652+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:59:51.650+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/create_tables_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/create_tables_dag.py", line 4, in <module>
    from create_tables_psql import create_tables
ImportError: cannot import name 'create_tables' from 'create_tables_psql' (/opt/airflow/dags/create_tables_psql.py)
[2023-09-08T17:59:51.653+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T17:59:51.677+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.119 seconds
[2023-09-08T18:00:22.398+0000] {processor.py:157} INFO - Started process (PID=170) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T18:00:22.400+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T18:00:22.402+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:00:22.402+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T18:00:22.427+0000] {processor.py:839} INFO - DAG(s) dict_keys(['create_tables_dag']) retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T18:00:22.623+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:00:22.623+0000] {manager.py:501} INFO - Created Permission View: can read on DAG:create_tables_dag
[2023-09-08T18:00:22.634+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:00:22.634+0000] {manager.py:501} INFO - Created Permission View: can edit on DAG:create_tables_dag
[2023-09-08T18:00:22.642+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:00:22.641+0000] {manager.py:501} INFO - Created Permission View: can delete on DAG:create_tables_dag
[2023-09-08T18:00:22.655+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:00:22.655+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-08T18:00:22.666+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:00:22.666+0000] {dag.py:2929} INFO - Creating ORM DAG for create_tables_dag
[2023-09-08T18:00:22.667+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:00:22.667+0000] {dag.py:3677} INFO - Setting next_dagrun for create_tables_dag to None, run_after=None
[2023-09-08T18:00:22.684+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.290 seconds
[2023-09-08T18:00:53.503+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T18:00:53.505+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T18:00:53.508+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:00:53.508+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T18:00:53.527+0000] {processor.py:839} INFO - DAG(s) dict_keys(['create_tables_dag']) retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T18:00:53.560+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:00:53.560+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-08T18:00:53.575+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:00:53.575+0000] {dag.py:3677} INFO - Setting next_dagrun for create_tables_dag to None, run_after=None
[2023-09-08T18:00:53.593+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.094 seconds
[2023-09-08T18:01:24.412+0000] {processor.py:157} INFO - Started process (PID=196) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T18:01:24.414+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T18:01:24.417+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:01:24.416+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T18:01:24.432+0000] {processor.py:839} INFO - DAG(s) dict_keys(['create_tables_dag']) retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T18:01:24.461+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:01:24.461+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-08T18:01:24.475+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:01:24.475+0000] {dag.py:3677} INFO - Setting next_dagrun for create_tables_dag to None, run_after=None
[2023-09-08T18:01:24.492+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.085 seconds
[2023-09-08T18:01:55.309+0000] {processor.py:157} INFO - Started process (PID=209) to work on /opt/airflow/dags/create_tables_dag.py
[2023-09-08T18:01:55.312+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/create_tables_dag.py for tasks to queue
[2023-09-08T18:01:55.315+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:01:55.315+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T18:01:55.332+0000] {processor.py:839} INFO - DAG(s) dict_keys(['create_tables_dag']) retrieved from /opt/airflow/dags/create_tables_dag.py
[2023-09-08T18:01:55.363+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:01:55.362+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-08T18:01:55.376+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:01:55.376+0000] {dag.py:3677} INFO - Setting next_dagrun for create_tables_dag to None, run_after=None
[2023-09-08T18:01:55.393+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/create_tables_dag.py took 0.089 seconds
