[2023-09-08T15:33:24.011+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:33:24.015+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:33:24.018+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:33:24.018+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:33:24.076+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:33:24.073+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:33:24.077+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:33:24.096+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.088 seconds
[2023-09-08T15:33:54.370+0000] {processor.py:157} INFO - Started process (PID=70) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:33:54.371+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:33:54.374+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:33:54.374+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:33:54.424+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:33:54.421+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:33:54.424+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:33:54.442+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.076 seconds
[2023-09-08T15:34:24.676+0000] {processor.py:157} INFO - Started process (PID=101) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:34:24.678+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:34:24.681+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:34:24.681+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:34:24.731+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:34:24.728+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:34:24.732+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:34:24.750+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.079 seconds
[2023-09-08T15:34:55.008+0000] {processor.py:157} INFO - Started process (PID=132) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:34:55.012+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:34:55.021+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:34:55.020+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:34:55.083+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:34:55.080+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:34:55.084+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:34:55.102+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.099 seconds
[2023-09-08T15:35:25.333+0000] {processor.py:157} INFO - Started process (PID=163) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:35:25.334+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:35:25.337+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:35:25.337+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:35:25.379+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:35:25.376+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:35:25.380+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:35:25.399+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.070 seconds
[2023-09-08T15:35:55.668+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:35:55.669+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:35:55.672+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:35:55.671+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:35:55.837+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:35:55.834+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:35:55.838+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:35:55.860+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.196 seconds
[2023-09-08T15:36:26.230+0000] {processor.py:157} INFO - Started process (PID=225) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:36:26.231+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:36:26.234+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:36:26.233+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:36:26.277+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:36:26.274+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:36:26.278+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:36:26.307+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.081 seconds
[2023-09-08T15:36:56.554+0000] {processor.py:157} INFO - Started process (PID=256) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:36:56.555+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:36:56.558+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:36:56.558+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:36:56.603+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:36:56.601+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:36:56.605+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:36:56.622+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.071 seconds
[2023-09-08T15:37:26.868+0000] {processor.py:157} INFO - Started process (PID=287) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:37:26.869+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:37:26.874+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:37:26.874+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:37:26.923+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:37:26.920+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:37:26.924+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:37:26.944+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.080 seconds
[2023-09-08T15:37:57.182+0000] {processor.py:157} INFO - Started process (PID=318) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:37:57.183+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:37:57.187+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:37:57.186+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:37:57.234+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:37:57.231+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:37:57.234+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:37:57.254+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.076 seconds
[2023-09-08T15:38:27.598+0000] {processor.py:157} INFO - Started process (PID=349) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:38:27.600+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:38:27.604+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:38:27.604+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:38:27.669+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:38:27.665+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:38:27.676+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:38:27.709+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.116 seconds
[2023-09-08T15:38:57.967+0000] {processor.py:157} INFO - Started process (PID=380) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:38:57.969+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:38:57.972+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:38:57.972+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:38:58.018+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:38:58.016+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:38:58.019+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:38:58.037+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.074 seconds
[2023-09-08T15:39:28.289+0000] {processor.py:157} INFO - Started process (PID=411) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:39:28.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:39:28.294+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:39:28.293+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:39:28.338+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:39:28.336+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:39:28.339+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:39:28.356+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.071 seconds
[2023-09-08T15:39:58.601+0000] {processor.py:157} INFO - Started process (PID=442) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:39:58.603+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:39:58.606+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:39:58.605+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:39:58.649+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:39:58.647+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:39:58.650+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:39:58.667+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.070 seconds
[2023-09-08T15:40:28.917+0000] {processor.py:157} INFO - Started process (PID=473) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:40:28.929+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:40:28.932+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:40:28.932+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:40:28.974+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:40:28.972+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:40:28.975+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:40:28.993+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.080 seconds
[2023-09-08T15:40:59.240+0000] {processor.py:157} INFO - Started process (PID=504) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:40:59.242+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:40:59.246+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:40:59.246+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:40:59.305+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:40:59.301+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:40:59.307+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:40:59.331+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.095 seconds
[2023-09-08T15:41:29.585+0000] {processor.py:157} INFO - Started process (PID=535) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:41:29.586+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:41:29.590+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:41:29.589+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:41:29.637+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:41:29.634+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:41:29.637+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:41:29.656+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.075 seconds
[2023-09-08T15:41:59.917+0000] {processor.py:157} INFO - Started process (PID=566) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:41:59.918+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:41:59.921+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:41:59.921+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:41:59.966+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:41:59.963+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:41:59.967+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:41:59.984+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.072 seconds
[2023-09-08T15:42:30.241+0000] {processor.py:157} INFO - Started process (PID=597) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:42:30.242+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:42:30.246+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:42:30.245+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:42:30.290+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:42:30.287+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:42:30.291+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:42:30.308+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.071 seconds
[2023-09-08T15:43:00.563+0000] {processor.py:157} INFO - Started process (PID=628) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:43:00.564+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:43:00.567+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:43:00.567+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:43:00.615+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:43:00.613+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:43:00.616+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:43:00.635+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.075 seconds
[2023-09-08T15:43:30.993+0000] {processor.py:157} INFO - Started process (PID=659) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:43:30.994+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:43:30.998+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:43:30.997+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:43:31.045+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:43:31.042+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:43:31.045+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:43:31.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.076 seconds
[2023-09-08T15:44:01.325+0000] {processor.py:157} INFO - Started process (PID=690) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:44:01.327+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:44:01.330+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:44:01.330+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:44:01.377+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:44:01.375+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:44:01.378+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:44:01.395+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.074 seconds
[2023-09-08T15:44:31.627+0000] {processor.py:157} INFO - Started process (PID=721) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:44:31.628+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:44:31.631+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:44:31.631+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:44:31.679+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:44:31.676+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:44:31.680+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:44:31.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.075 seconds
[2023-09-08T15:45:01.955+0000] {processor.py:157} INFO - Started process (PID=752) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:45:01.956+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:45:01.960+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:45:01.959+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:45:02.005+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:45:02.002+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:45:02.006+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:45:02.024+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.073 seconds
[2023-09-08T15:45:32.268+0000] {processor.py:157} INFO - Started process (PID=783) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:45:32.270+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:45:32.273+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:45:32.272+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:45:32.317+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:45:32.314+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 90, in <module>
    conn = duckdb.connect('my_database.duckdb')
duckdb.IOException: IO Error: Could not set lock on file "/opt/airflow/my_database.duckdb": Resource temporarily unavailable
[2023-09-08T15:45:32.318+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:45:32.335+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.071 seconds
[2023-09-08T15:48:25.690+0000] {processor.py:157} INFO - Started process (PID=41) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:48:25.691+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:48:25.694+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:48:25.694+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:48:25.706+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:48:25.703+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-09-08T15:48:25.706+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:48:25.726+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.040 seconds
[2023-09-08T15:48:55.997+0000] {processor.py:157} INFO - Started process (PID=52) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:48:55.998+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:48:56.001+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:48:56.001+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:48:56.013+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:48:56.010+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-09-08T15:48:56.013+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:48:56.033+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.039 seconds
[2023-09-08T15:49:26.347+0000] {processor.py:157} INFO - Started process (PID=63) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:49:26.349+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:49:26.353+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:49:26.353+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:49:26.368+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:49:26.365+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-09-08T15:49:26.369+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:49:26.391+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.048 seconds
[2023-09-08T15:49:56.689+0000] {processor.py:157} INFO - Started process (PID=74) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:49:56.690+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:49:56.693+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:49:56.692+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:49:56.704+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:49:56.702+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
  File "/opt/airflow/dags/duckdb_handler.py", line 1, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
[2023-09-08T15:49:56.705+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:49:56.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.044 seconds
[2023-09-08T15:50:26.950+0000] {processor.py:157} INFO - Started process (PID=84) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:50:26.952+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:50:26.953+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:50:26.953+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:50:26.965+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:50:26.963+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
ModuleNotFoundError: No module named 'duckdb_handler'
[2023-09-08T15:50:26.966+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:50:26.985+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.040 seconds
[2023-09-08T15:50:57.233+0000] {processor.py:157} INFO - Started process (PID=94) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:50:57.234+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:50:57.235+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:50:57.235+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:50:57.246+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:50:57.244+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
ModuleNotFoundError: No module named 'duckdb_handler'
[2023-09-08T15:50:57.247+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:50:57.266+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.038 seconds
[2023-09-08T15:51:27.533+0000] {processor.py:157} INFO - Started process (PID=104) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:51:27.543+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:51:27.544+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:51:27.544+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:51:27.556+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:51:27.554+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
ModuleNotFoundError: No module named 'duckdb_handler'
[2023-09-08T15:51:27.556+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:51:27.576+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.046 seconds
[2023-09-08T15:51:57.852+0000] {processor.py:157} INFO - Started process (PID=114) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:51:57.853+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:51:57.854+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:51:57.854+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:51:57.867+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:51:57.865+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
ModuleNotFoundError: No module named 'duckdb_handler'
[2023-09-08T15:51:57.868+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:51:57.888+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.040 seconds
[2023-09-08T15:52:28.136+0000] {processor.py:157} INFO - Started process (PID=124) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:52:28.137+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:52:28.138+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:52:28.138+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:52:28.151+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:52:28.149+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
ModuleNotFoundError: No module named 'duckdb_handler'
[2023-09-08T15:52:28.152+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:52:28.170+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.038 seconds
[2023-09-08T15:52:58.403+0000] {processor.py:157} INFO - Started process (PID=134) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:52:58.404+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:52:58.405+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:52:58.405+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:52:58.415+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:52:58.414+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
ModuleNotFoundError: No module named 'duckdb_handler'
[2023-09-08T15:52:58.417+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:52:58.434+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.035 seconds
[2023-09-08T15:53:28.764+0000] {processor.py:157} INFO - Started process (PID=144) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:53:28.766+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:53:28.767+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:53:28.766+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:53:28.779+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:53:28.777+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
ModuleNotFoundError: No module named 'duckdb_handler'
[2023-09-08T15:53:28.780+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:53:28.799+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.039 seconds
[2023-09-08T15:53:59.058+0000] {processor.py:157} INFO - Started process (PID=154) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:53:59.060+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:53:59.061+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:53:59.061+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:53:59.072+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:53:59.070+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
ModuleNotFoundError: No module named 'duckdb_handler'
[2023-09-08T15:53:59.073+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:53:59.091+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.036 seconds
[2023-09-08T15:54:29.341+0000] {processor.py:157} INFO - Started process (PID=164) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:54:29.343+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:54:29.344+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:54:29.343+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:54:29.354+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:54:29.352+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
ModuleNotFoundError: No module named 'duckdb_handler'
[2023-09-08T15:54:29.355+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:54:29.373+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.035 seconds
[2023-09-08T15:54:59.638+0000] {processor.py:157} INFO - Started process (PID=174) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:54:59.639+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:54:59.641+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:54:59.640+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:54:59.653+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:54:59.651+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
ModuleNotFoundError: No module named 'duckdb_handler'
[2023-09-08T15:54:59.654+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:54:59.673+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.041 seconds
[2023-09-08T15:55:29.952+0000] {processor.py:157} INFO - Started process (PID=191) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:55:29.953+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:55:29.954+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:55:29.954+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:55:29.964+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:55:29.963+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from duckdb_handler import ingest_excel_to_duckdb
ModuleNotFoundError: No module named 'duckdb_handler'
[2023-09-08T15:55:29.967+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:55:29.987+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.039 seconds
[2023-09-08T15:56:00.267+0000] {processor.py:157} INFO - Started process (PID=201) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:56:00.269+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:56:00.272+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:56:00.271+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:56:00.293+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:56:00.291+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from postgres_handler import ingest_excel  # <-- Updated this import
ModuleNotFoundError: No module named 'postgres_handler'
[2023-09-08T15:56:00.294+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:56:00.315+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.053 seconds
[2023-09-08T15:56:23.515+0000] {processor.py:157} INFO - Started process (PID=203) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:56:23.516+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:56:23.518+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:56:23.517+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:56:23.873+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:56:23.869+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/path/to/your/excel/file.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:56:23.874+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:56:23.892+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.381 seconds
[2023-09-08T15:56:54.768+0000] {processor.py:157} INFO - Started process (PID=214) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:56:54.770+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T15:56:54.772+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:56:54.772+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:56:55.103+0000] {logging_mixin.py:151} INFO - [2023-09-08T15:56:55.098+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T15:56:55.104+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T15:56:55.123+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.359 seconds
[2023-09-08T16:01:36.560+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:01:36.562+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T16:01:36.565+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:01:36.564+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:01:37.016+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:01:37.012+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:01:37.017+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:01:37.036+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.479 seconds
[2023-09-08T16:02:07.428+0000] {processor.py:157} INFO - Started process (PID=53) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:02:07.430+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T16:02:07.432+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:02:07.432+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:02:07.872+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:02:07.869+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:02:07.873+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:02:07.888+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.464 seconds
[2023-09-08T16:02:38.157+0000] {processor.py:157} INFO - Started process (PID=66) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:02:38.158+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T16:02:38.160+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:02:38.160+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:02:38.594+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:02:38.591+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:02:38.595+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:02:38.611+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.458 seconds
[2023-09-08T16:03:08.841+0000] {processor.py:157} INFO - Started process (PID=79) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:03:08.843+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T16:03:08.845+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:03:08.845+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:03:09.242+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:03:09.238+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:03:09.244+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:03:09.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.420 seconds
[2023-09-08T16:03:39.526+0000] {processor.py:157} INFO - Started process (PID=92) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:03:39.528+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T16:03:39.532+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:03:39.531+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:03:39.939+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:03:39.935+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:03:39.940+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:03:39.957+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.435 seconds
[2023-09-08T16:04:10.202+0000] {processor.py:157} INFO - Started process (PID=105) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:04:10.204+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T16:04:10.206+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:04:10.206+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:04:10.655+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:04:10.651+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:04:10.657+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:04:10.673+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.475 seconds
[2023-09-08T16:04:40.914+0000] {processor.py:157} INFO - Started process (PID=118) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:04:40.916+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T16:04:40.918+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:04:40.918+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:04:41.338+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:04:41.333+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:04:41.339+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:04:41.355+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.445 seconds
[2023-09-08T16:05:11.760+0000] {processor.py:157} INFO - Started process (PID=131) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:05:11.762+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T16:05:11.766+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:05:11.765+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:05:12.056+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:05:12.052+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:05:12.057+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:05:12.073+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.316 seconds
[2023-09-08T16:05:42.365+0000] {processor.py:157} INFO - Started process (PID=145) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:05:42.367+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T16:05:42.370+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:05:42.370+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:05:42.693+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:05:42.690+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:05:42.695+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:05:42.712+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.352 seconds
[2023-09-08T16:06:13.028+0000] {processor.py:157} INFO - Started process (PID=158) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:06:13.029+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T16:06:13.032+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:06:13.032+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:06:13.331+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:06:13.328+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:06:13.332+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:06:13.349+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.326 seconds
[2023-09-08T16:06:39.649+0000] {processor.py:157} INFO - Started process (PID=171) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:06:39.651+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T16:06:39.655+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:06:39.654+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:06:40.036+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:06:40.031+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:06:40.038+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:06:40.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.419 seconds
[2023-09-08T16:07:21.936+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:07:21.938+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T16:07:21.942+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:07:21.941+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:07:22.395+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:07:22.391+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:07:22.396+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:07:22.417+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.486 seconds
[2023-09-08T16:07:52.747+0000] {processor.py:157} INFO - Started process (PID=51) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:07:52.749+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T16:07:52.752+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:07:52.752+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:07:53.216+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:07:53.213+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:07:53.217+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:07:53.233+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.490 seconds
[2023-09-08T16:08:23.559+0000] {processor.py:157} INFO - Started process (PID=64) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:08:23.561+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T16:08:23.564+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:08:23.563+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:08:23.960+0000] {logging_mixin.py:151} INFO - [2023-09-08T16:08:23.957+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T16:08:23.961+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T16:08:23.976+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.422 seconds
[2023-09-08T17:45:25.516+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:45:25.517+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:45:25.520+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:45:25.520+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:45:25.958+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:45:25.955+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:45:25.960+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:45:25.979+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.468 seconds
[2023-09-08T17:45:56.323+0000] {processor.py:157} INFO - Started process (PID=52) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:45:56.324+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:45:56.327+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:45:56.327+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:45:56.715+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:45:56.710+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:45:56.716+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:45:56.732+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.413 seconds
[2023-09-08T17:46:27.012+0000] {processor.py:157} INFO - Started process (PID=65) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:46:27.013+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:46:27.016+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:46:27.016+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:46:27.399+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:46:27.395+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:46:27.400+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:46:27.414+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.406 seconds
[2023-09-08T17:46:57.758+0000] {processor.py:157} INFO - Started process (PID=78) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:46:57.759+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:46:57.763+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:46:57.762+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:46:58.226+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:46:58.223+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:46:58.227+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:46:58.243+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.489 seconds
[2023-09-08T17:47:28.567+0000] {processor.py:157} INFO - Started process (PID=91) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:47:28.569+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:47:28.572+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:47:28.571+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:47:28.973+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:47:28.968+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:47:28.973+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:47:28.988+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.425 seconds
[2023-09-08T17:47:59.294+0000] {processor.py:157} INFO - Started process (PID=104) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:47:59.296+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:47:59.300+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:47:59.299+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:47:59.688+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:47:59.685+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:47:59.690+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:47:59.708+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.417 seconds
[2023-09-08T17:48:29.941+0000] {processor.py:157} INFO - Started process (PID=117) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:48:29.942+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:48:29.945+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:48:29.944+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:48:30.332+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:48:30.328+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:48:30.333+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:48:30.349+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.413 seconds
[2023-09-08T17:49:00.697+0000] {processor.py:157} INFO - Started process (PID=130) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:49:00.699+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:49:00.702+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:49:00.702+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:49:01.131+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:49:01.128+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:49:01.132+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:49:01.147+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.455 seconds
[2023-09-08T17:49:31.733+0000] {processor.py:157} INFO - Started process (PID=143) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:49:31.735+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:49:31.739+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:49:31.738+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:49:32.030+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:49:32.027+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:49:32.031+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:49:32.047+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.319 seconds
[2023-09-08T17:50:02.397+0000] {processor.py:157} INFO - Started process (PID=156) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:50:02.399+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:50:02.403+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:50:02.402+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:50:02.710+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:50:02.707+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:50:02.711+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:50:02.729+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.336 seconds
[2023-09-08T17:50:33.099+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:50:33.101+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:50:33.104+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:50:33.104+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:50:33.373+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:50:33.369+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:50:33.374+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:50:33.389+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.293 seconds
[2023-09-08T17:51:03.686+0000] {processor.py:157} INFO - Started process (PID=182) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:51:03.687+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:51:03.690+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:51:03.690+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:51:03.980+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:51:03.977+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 47, in ingest_excel
    with get_connection() as conn:
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 16, in get_connection
    return psycopg2.connect(**DATABASE_CONFIG)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2023-09-08T17:51:03.981+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:51:03.998+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.316 seconds
[2023-09-08T17:51:34.358+0000] {processor.py:157} INFO - Started process (PID=196) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:51:34.360+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:51:34.363+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:51:34.362+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:51:34.784+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:51:34.776+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 142, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 478, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1513, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 548, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 145, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2023-09-08T17:51:34.786+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:51:34.839+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.485 seconds
[2023-09-08T17:52:22.419+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:52:22.421+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:52:22.423+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:52:22.423+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:52:22.905+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:52:22.900+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 142, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 478, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1513, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 548, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 145, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2023-09-08T17:52:22.906+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:52:22.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.514 seconds
[2023-09-08T17:52:53.350+0000] {processor.py:157} INFO - Started process (PID=52) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:52:53.352+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:52:53.355+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:52:53.355+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:52:53.791+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:52:53.788+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 142, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 478, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1513, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 548, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 145, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2023-09-08T17:52:53.792+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:52:53.807+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.461 seconds
[2023-09-08T17:53:24.177+0000] {processor.py:157} INFO - Started process (PID=65) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:53:24.178+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:53:24.181+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:53:24.180+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:53:24.602+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:53:24.599+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 142, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 478, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1513, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 548, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 145, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2023-09-08T17:53:24.604+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:53:24.618+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.446 seconds
[2023-09-08T17:53:54.979+0000] {processor.py:157} INFO - Started process (PID=78) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:53:54.980+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:53:54.983+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:53:54.982+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:53:55.437+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:53:55.434+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 142, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 478, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1513, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 548, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 145, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2023-09-08T17:53:55.438+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:53:55.454+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.480 seconds
[2023-09-08T17:54:25.713+0000] {processor.py:157} INFO - Started process (PID=91) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:54:25.715+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:54:25.717+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:54:25.717+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:54:26.162+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:54:26.158+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 142, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 478, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1513, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 548, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/compat/_optional.py", line 145, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2023-09-08T17:54:26.164+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:54:26.182+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.472 seconds
[2023-09-08T17:55:43.093+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:55:43.095+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:55:43.100+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:55:43.100+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:55:43.754+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:55:43.751+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 746, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'country_data' not found
[2023-09-08T17:55:43.755+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:55:43.821+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.734 seconds
[2023-09-08T17:56:14.220+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:56:14.222+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:56:14.227+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:56:14.227+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:56:14.899+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:56:14.894+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 746, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'country_data' not found
[2023-09-08T17:56:14.900+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:56:14.918+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.704 seconds
[2023-09-08T17:56:45.289+0000] {processor.py:157} INFO - Started process (PID=68) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:56:45.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:56:45.294+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:56:45.293+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:56:45.953+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:56:45.948+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 746, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'country_data' not found
[2023-09-08T17:56:45.956+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:56:45.981+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.697 seconds
[2023-09-08T17:57:16.386+0000] {processor.py:157} INFO - Started process (PID=81) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:57:16.387+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:57:16.390+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:57:16.390+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:57:16.997+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:57:16.992+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 746, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'country_data' not found
[2023-09-08T17:57:16.999+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:57:17.017+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.636 seconds
[2023-09-08T17:57:47.504+0000] {processor.py:157} INFO - Started process (PID=94) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:57:47.506+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:57:47.508+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:57:47.508+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:57:48.011+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:57:48.006+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 746, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'country_data' not found
[2023-09-08T17:57:48.013+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:57:48.037+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.538 seconds
[2023-09-08T17:58:18.358+0000] {processor.py:157} INFO - Started process (PID=114) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:58:18.360+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:58:18.365+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:58:18.364+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:58:18.891+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:58:18.887+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 746, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'country_data' not found
[2023-09-08T17:58:18.894+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:58:18.916+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.563 seconds
[2023-09-08T17:58:49.214+0000] {processor.py:157} INFO - Started process (PID=127) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:58:49.217+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:58:49.220+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:58:49.219+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:58:49.692+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:58:49.688+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 746, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'country_data' not found
[2023-09-08T17:58:49.693+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:58:49.710+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.501 seconds
[2023-09-08T17:59:20.081+0000] {processor.py:157} INFO - Started process (PID=140) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:59:20.082+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:59:20.085+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:59:20.085+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:59:20.528+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:59:20.521+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 746, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'country_data' not found
[2023-09-08T17:59:20.530+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:59:20.549+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.472 seconds
[2023-09-08T17:59:50.950+0000] {processor.py:157} INFO - Started process (PID=154) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:59:50.952+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T17:59:50.955+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:59:50.954+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:59:51.504+0000] {logging_mixin.py:151} INFO - [2023-09-08T17:59:51.499+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 746, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'country_data' not found
[2023-09-08T17:59:51.506+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T17:59:51.536+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.590 seconds
[2023-09-08T18:00:21.853+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T18:00:21.854+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T18:00:21.857+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:00:21.857+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T18:00:22.351+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:00:22.346+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 746, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'country_data' not found
[2023-09-08T18:00:22.353+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T18:00:22.371+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.524 seconds
[2023-09-08T18:00:52.946+0000] {processor.py:157} INFO - Started process (PID=180) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T18:00:52.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T18:00:52.951+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:00:52.950+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T18:00:53.454+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:00:53.449+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 746, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'country_data' not found
[2023-09-08T18:00:53.455+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T18:00:53.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.531 seconds
[2023-09-08T18:01:23.861+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T18:01:23.863+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T18:01:23.867+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:01:23.866+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T18:01:24.370+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:01:24.367+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 746, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'country_data' not found
[2023-09-08T18:01:24.371+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T18:01:24.389+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.531 seconds
[2023-09-08T18:01:54.756+0000] {processor.py:157} INFO - Started process (PID=206) to work on /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T18:01:54.758+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/ingest_xl_data_dag.py for tasks to queue
[2023-09-08T18:01:54.761+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:01:54.761+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T18:01:55.229+0000] {logging_mixin.py:151} INFO - [2023-09-08T18:01:55.225+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/ingest_xl_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ingest_xl_data_dag.py", line 7, in <module>
    from ingest_data_to_psql import ingest_excel  # <-- Updated this import
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 71, in <module>
    ingest_excel('/opt/airflow/dags/WordbankEconomicData_Trimmed_v2.xlsx')
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 54, in ingest_excel
    insert_data_from_excel(file_path, 'country_data', conn)
  File "/opt/airflow/dags/ingest_data_to_psql.py", line 26, in insert_data_from_excel
    data = pd.read_excel(file_path, sheet_name=table_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 746, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'country_data' not found
[2023-09-08T18:01:55.230+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/ingest_xl_data_dag.py
[2023-09-08T18:01:55.276+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/ingest_xl_data_dag.py took 0.523 seconds
